[server]
headless = true
port = $PORT
enableCORS = false
[google_service_account]
type = "service_account"
project_id = "soopa-apps-project"
private_key_id = "e98f35ee538779f4bf9eebc99b63078efc0736b6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC8fdjCRKhoSec9
LTrLYw6dAV1jnI080aqrwflgBszXLscO7zgoTkoDFCFNcj+la5lVV4SfTcV4O1/3
VCsF157TlcnFFHcY2yLcTsR9L7e2Cyu4DYjkqqRGuvXe99K4BHxeNG5ZRrkU715E
VIsqPG6wE4DNBTVNG+2TIuSzkgcBRAV7R5lYzcXQ6zdp2bWOfEtOtT6xJpmXYWxy
dzHoMWC/obsVCatE8141MAnL4U81KJyW6YXfn7fPoDnatIYlOItAWxfGX6+yBXkT
ISekVa5jTq/viiZDk0935XB8bHZnpwbjk5zHAY3oY5SzDAtjuOl2LeiivevWcZBT
akVWu3+3AgMBAAECggEAVshEK5FLzhQ0jFSOLMUTHdNaiXmzB0zrHMAmjgEjf3EQ
gf4+p0QATHGQsaUHy6QCCSpNq8C1SZlgojFUy5BOFlFw/7Vf7gg6gR8c1RxKo1x6
SPemTs2H6+65M+p60HF0RzUxlxX6MbrRdnlMR2piddvM4dfjhfh1Rdh7Xne9lOVO
jvtIVUUSjyQJhuYch4hbpuxHLBl0lyGY6SDr1nXv4ryFTj1pqY4y3+313iMyBicy
anRZ7gPh5GA0imiKS8QJwItduc+ZbM91J5hwOFOXVq0BFcNFkPAT9JAsx6cjNIp3
OAwQWhZ0ZVSLQULiZNxSicWxNo4S7y1CbeXKojfPAQKBgQD0J30pDNr95DU8G6B/
8VY36iN5PSpA3LkViBcsjB7Zk4fSwRM55Q6vaxoYK2SZXb/yjg683boDnI+ip/2i
MLZQ9Csqb63yymN7vV2Etf333Lq/uf42dKKJ6oh0OfaPDA4iZXCkTW4mTGuLgHRq
k8NEWmzzc2ucnX/1ZfLvMsH+twKBgQDFowBQuNcpcOUY/QG0umhdshc7dAov466A
wyMD3g/NN4ar1TxOsPC/fD+LPxZVY6xQGrUeyelEoRIrXcnRLlsYCZWweJT5aClz
Hg0t/GPSqEHsRkHyaUfjmAKHCLI2Cyo5z3XLfF1RUqpT65LVT5c8tW55TdHs9spR
YWKC95GHAQKBgBZaRysq8iGscvM91EPiZHJaDUVcRDIMAyXlf7mkWm6xAw5Yftoe
Dmog9BKiZmNkId6jAtZntk/+VWge2SmwLADdWdZYwyQnQ1Rg0d8EimvW2YIUFSIH
K5pUzolVhS0zfVfI0bc5H4yCEpaC/CWFwarQXIktV/zOrphY7RTZIMmhAoGBALdP
MpGsf9SuI7ADqztn0jllX2sDfBdjBI3lcGq74sgjAkQKqb8LGqFgqseKojpdEovR
2cBO4o+HHgUfHntolZE8Ap0Fmpeh5yAg9XR7rlLLQSnXGH+w6r7MVTvN8w1xWZ75
L3anSR6On/DqhOxYwBvM5ESay2UQmiLVQrvayB4BAoGARWeIdXBXB305R3R2NRi6
srOuZlLlqhLV/6Nn7sNhEdlNdY+yxPb+YUVFGgTEX+9+1JJpioH8MLzKnvej5haS
h291l7GHBIqlDhoN87zA5sNCh3bGVDqeU54XR57ppJIStkYchUp5/baUSuYlUZfH
3LbO0lWUHCRqZ6hHGZxxqvg=
-----END PRIVATE KEY-----"""
client_email = "loginsoopaapps@soopa-apps-project.iam.gserviceaccount.com"
client_id = "109236722127799438733"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/loginsoopaapps%40soopa-apps-project.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
CLOUDINARY_CLOUD_NAME = "dbxmliyzr"
CLOUDINARY_API_KEY = "157236951965868"
CLOUDINARY_API_SECRET = "4_GPqScoK-9rup4Eb_GS1fbxgjs"
